---
# role: ansible-role-sysctl
# file: .travis.yml

language: python

python:
  - "3.9"

branches:
  only:
    - main

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install ansible yamllint ansible-lint

script:
  - yamllint .
  - ansible-lint
