---
# role: ansible-role-sysctl
# file: tasks/main.yml

- name: "Tasks for ansible-role-sysctl"
  block:
    - name: "Install packages for ansible-role-sysctl"
      package:
        name: "{{ sysctl_packages }}"
        state: present

    - name: "Configure /etc/sysctl.conf"
      template:
        src: etc/sysctl.conf.j2
        dest: /etc/sysctl.conf
        mode: 0640
        owner: root
        group: root
        backup: "{{ sysctl_backup }}"
      when: sysctl_conf | length > 0
      notify: reload sysctl

    - name: "Create /etc/sysctl.d/"
      file:
        path: /etc/sysctl.d/
        state: directory
        mode: 0750
        owner: root
        group: root

    - name: "Configure /etc/sysctl.d/ files"
      template:
        src: etc/sysctl.d/sysctl.d.conf.j2
        dest: "/etc/sysctl.d/{{ item.file }}"
        mode: 0640
        owner: root
        group: root
        backup: "{{ sysctl_backup }}"
      loop: "{{ sysctl_d }}"
      notify: reload sysctl
  when: sysctl_role_enabled | bool
