---
# role: ansible-role-sysctl
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: sysctl-alpine
    box: "generic/alpine312"
    cpus: 2
    memory: 1024
  - name: sysctl-amazon
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: sysctl-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: sysctl-centos
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: sysctl-debian
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: sysctl-fedora
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: sysctl-opensuse
    box: "generic/opensuse15"
    cpus: 2
    memory: 1024
  - name: sysctl-oracle
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: sysctl-ubuntu
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        sysctl_role_enabled: true
verifier:
  name: ansible
