---
# role: ansible-role-sysctl
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: sysctl-default
    image: ${MOLECULE_IMG:-"jam82/molecule-debian:11"}
    command: ${MOLECULE_IMG_CMD:-""}
    pre_build_image: true
    tty: false
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        sysctl_role_enabled: true
verifier:
  name: ansible
