---
# role: ansible-role-sysctl
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  vars:
    baseline_role_enabled: false
    sysctl_role_enabled: true
  roles:
    - role: ../../../../
